# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/kt',
                'doc_host': 'https://amaiya.github.io',
                'git_url': 'https://github.com/amaiya/kt',
                'lib_path': 'kt'},
  'syms': {'kt.core': {'kt.core.foo': ('core.html#foo', 'kt/core.py')}}}
